# Generated by Django 5.2.2 on 2025-07-12 21:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_alter_wallet_message_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MinerTokenEarnings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miner_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('total_aius_earned', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('total_aius_sold', models.DecimalField(decimal_places=18, default=0, max_digits=36)),
                ('total_usd_from_sales', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('first_earning_date', models.DateTimeField(blank=True, null=True)),
                ('last_earning_date', models.DateTimeField(blank=True, null=True)),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('last_analyzed', models.DateTimeField(blank=True, null=True)),
                ('needs_reanalysis', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_usd_from_sales'],
            },
        ),
        migrations.CreateModel(
            name='ScanStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_scanned_block', models.BigIntegerField(default=0)),
                ('last_scan_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('scan_in_progress', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Scan statuses',
            },
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='connected_at',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='last_used',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='message_hash',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='signature',
        ),
        migrations.AddField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='wallet',
            table=None,
        ),
        migrations.CreateModel(
            name='ArbiusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('task_id', models.CharField(db_index=True, max_length=66)),
                ('block_number', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('cid', models.CharField(db_index=True, max_length=100)),
                ('ipfs_url', models.URLField()),
                ('image_url', models.URLField()),
                ('model_id', models.CharField(blank=True, help_text='The AI model used to generate this image', max_length=66, null=True)),
                ('prompt', models.TextField(blank=True, help_text='The prompt used to generate this image', null=True)),
                ('input_parameters', models.JSONField(blank=True, help_text='Full input parameters including prompt and other settings', null=True)),
                ('solution_provider', models.CharField(default='0x0000000000000000000000000000000000000000', help_text='Address of the miner who provided the solution/image', max_length=42)),
                ('task_submitter', models.CharField(blank=True, help_text='Address of the user who originally submitted the task/prompt', max_length=42, null=True)),
                ('miner_address', models.CharField(blank=True, help_text='DEPRECATED: Use solution_provider instead', max_length=42, null=True)),
                ('owner_address', models.CharField(blank=True, max_length=42, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('discovered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_accessible', models.BooleanField(default=True)),
                ('last_checked', models.DateTimeField(default=django.utils.timezone.now)),
                ('ipfs_gateway', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='playground__timesta_486bd9_idx'), models.Index(fields=['cid'], name='playground__cid_27f28f_idx'), models.Index(fields=['transaction_hash'], name='playground__transac_fa5dcf_idx')],
            },
        ),
        migrations.CreateModel(
            name='MinerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, help_text='Ethereum wallet address of the miner', max_length=42, unique=True)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='When this miner was first identified')),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now, help_text='When this miner was last seen submitting solutions/commitments')),
                ('total_solutions', models.PositiveIntegerField(default=0, help_text='Total number of solutions submitted by this miner')),
                ('total_commitments', models.PositiveIntegerField(default=0, help_text='Total number of commitments submitted by this miner')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this miner is currently considered active')),
            ],
            options={
                'verbose_name_plural': 'Miner addresses',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['wallet_address'], name='playground__wallet__7d2b37_idx'), models.Index(fields=['last_seen'], name='playground__last_se_ca61f9_idx'), models.Index(fields=['is_active'], name='playground__is_acti_5cc961_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_hash', models.CharField(db_index=True, max_length=66, unique=True)),
                ('from_address', models.CharField(db_index=True, max_length=42)),
                ('to_address', models.CharField(db_index=True, max_length=42)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=36)),
                ('block_number', models.BigIntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('gas_price', models.BigIntegerField(blank=True, null=True)),
                ('gas_used', models.BigIntegerField(blank=True, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('sale_price_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('exchange_address', models.CharField(blank=True, max_length=42, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['transaction_hash'], name='playground__transac_2cda46_idx'), models.Index(fields=['from_address'], name='playground__from_ad_5a8f2d_idx'), models.Index(fields=['to_address'], name='playground__to_addr_dd2524_idx'), models.Index(fields=['timestamp'], name='playground__timesta_cb9493_idx'), models.Index(fields=['is_sale'], name='playground__is_sale_6bd801_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('twitter_handle', models.CharField(blank=True, max_length=50, null=True)),
                ('total_images_created', models.IntegerField(default=0)),
                ('total_upvotes_received', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['wallet_address'], name='playground__wallet__000f8c_idx'), models.Index(fields=['created_at'], name='playground__created_7ee822_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42)),
                ('content', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='playground.arbiusimage')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet_address'], name='playground__wallet__d124e5_idx'), models.Index(fields=['created_at'], name='playground__created_855aa2_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImageUpvote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='playground.arbiusimage')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet_address'], name='playground__wallet__c671ae_idx'), models.Index(fields=['created_at'], name='playground__created_73bfbe_idx')],
                'unique_together': {('image', 'wallet_address')},
            },
        ),
    ]
