# Generated by Django 5.2.2 on 2025-07-15 21:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_minertokenearnings_scanstatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_address', models.CharField(db_index=True, max_length=42)),
                ('emoji', models.CharField(choices=[('❤️', 'Heart'), ('😂', 'Laugh'), ('😮', 'Wow'), ('😢', 'Sad'), ('👍', 'Thumbs Up'), ('👎', 'Thumbs Down'), ('🔥', 'Fire'), ('💯', '100')], max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='playground.arbiusimage')),
            ],
            options={
                'indexes': [models.Index(fields=['wallet_address'], name='playground__wallet__b324d3_idx'), models.Index(fields=['created_at'], name='playground__created_80ad0c_idx'), models.Index(fields=['emoji'], name='playground__emoji_e23e86_idx')],
                'unique_together': {('image', 'wallet_address', 'emoji')},
            },
        ),
    ]
